const h = value => String(value ?? '').replace(/[&<>'"]/g, x => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[x]));
const bundledEnv = typeof __APP_ENV__ === 'undefined' ? {} : __APP_ENV__;
const config = env => ({ url: env.SUPABASE_URL || bundledEnv.SUPABASE_URL || '', key: env.SUPABASE_PUBLISHABLE_KEY || bundledEnv.SUPABASE_PUBLISHABLE_KEY || '', siteUrl: env.PUBLIC_SITE_URL || (env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${env.VERCEL_PROJECT_PRODUCTION_URL}` : ''), adsenseClientId: env.ADSENSE_CLIENT_ID || bundledEnv.ADSENSE_CLIENT_ID || '', adsenseSlotId: env.ADSENSE_SLOT_ID || bundledEnv.ADSENSE_SLOT_ID || '' });
const headers = { 'Content-Type':'text/html; charset=utf-8', 'Cache-Control':'no-store', 'X-Content-Type-Options':'nosniff', 'Referrer-Policy':'strict-origin-when-cross-origin', 'Permissions-Policy':'camera=(), microphone=(), geolocation=()', 'Content-Security-Policy':"default-src 'self'; script-src 'self' https://pagead2.googlesyndication.com; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.supabase.co https://pagead2.googlesyndication.com https://googleads.g.doubleclick.net; img-src 'self' https: data:; frame-src https://googleads.g.doubleclick.net https://tpc.googlesyndication.com; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'" };
function shell(title, content, env) { const c=config(env), adsenseVerification=c.adsenseClientId?`<meta name="google-adsense-account" content="${h(c.adsenseClientId)}">`:''; return new Response(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${h(title)} · PromptHub</title><link rel="stylesheet" href="/css/v1.css?v=creator-v3">${adsenseVerification}<meta name="prompthub-supabase-url" content="${h(c.url)}"><meta name="prompthub-supabase-key" content="${h(c.key)}"><meta name="prompthub-site-url" content="${h(c.siteUrl)}"><meta name="prompthub-adsense-client" content="${h(c.adsenseClientId)}"><meta name="prompthub-adsense-slot" content="${h(c.adsenseSlotId)}"></head><body><header class="topbar"><a class="brand" href="/">Prompt<span>Hub</span><small>CREATORS</small></a></header><main>${content}</main><footer><a class="brand" href="/">Prompt<span>Hub</span></a><span>Creator prompt pages</span><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div></footer><script type="module" src="/js/supabase-portal.js?v=creator-v9"></script></body></html>`,{headers}); }
const fail=(message,status,env)=>shell('PromptHub',`<section class="card"><h1>Something went wrong</h1><p>${h(message)}</p></section>`,env).then?null:null;
async function db(env, path) { if (path.includes('handle=eq.demo')) return [{id:'demo',handle:'demo',display_name:'PromptHub Demo',bio:'Try the keyword saree to see how a creator page works.'}]; if (path.includes('creator_id=eq.demo') && path.includes('keyword=eq.saree')) return [{keyword:'saree',title:'Shadowed Saree Elegance',prompt:'Create an editorial portrait of an adult woman wearing an elegant silk saree beside a softly lit window. Use warm natural light, detailed fabric textures and a balanced vertical composition.'}]; const c=config(env); if(!c.url||!c.key) throw new Error('Supabase runtime configuration is missing.'); const response=await fetch(c.url+'/rest/v1/'+path,{headers:{apikey:c.key,Authorization:'Bearer '+c.key}}); if(!response.ok) throw new Error('Data could not load.'); return response.json(); }
function portal(kind,env){
  const admin=kind==='admin';
  const creatorMagic=`<form class="card auth-form" data-magic-link><label>Email<input name="email" type="email" autocomplete="email" required></label><button class="button">Continue with email</button><p class="muted" data-magic-message></p></form>`;
  const adminLogin=`<form class="card auth-form" data-auth="admin"><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Password<input name="password" type="password" minlength="8" autocomplete="current-password" required></label><div class="actions"><button class="button" name="mode" value="signin">Sign in</button></div><p class="muted" data-auth-message></p></form>`;
  const login=admin?adminLogin:creatorMagic;
  return shell(admin?'Admin login':'Creator portal',`<section class="creator-portal"><div><p class="eyebrow">${admin?'ADMIN PORTAL':'CREATOR PORTAL'}</p><h1>${admin?'Manage creators and link activity.':'Start your creator page.'}</h1><p class="lead">${admin?'Sign in with the administrator account.':'Enter your email and we will send a secure sign-in link. No password required.'}</p>${login}</div><div class="card portal-steps"><span class="step-num">01</span><h2>${admin?'Secure role':'Check your inbox'}</h2><p>${admin?'Only users assigned the admin database role can open the admin dashboard.':'Open the one-time link we send to your email.'}</p><span class="step-num">02</span><h2>${admin?'Review creator pages':'Create your page'}</h2><p>${admin?'Watch creator signups, public link visits and prompt-copy activity.':'Add prompts with the keywords you mention in your reels.'}</p><span class="step-num">03</span><h2>${admin?'Keep beta clean':'Share one link'}</h2><p>${admin?'Help the first creators launch without confusing setup.':'Put your PromptHub link in bio. Viewers enter the keyword and copy the prompt.'}</p></div></section>`,env);
}
function passwordSetup(env){ return shell('Set your password',`<section class="narrow"><p class="eyebrow">PROMPTHUB SECURITY</p><h1>Create a new password</h1><p class="lead compact">Choose a password for PromptHub. It is separate from your Gmail password.</p><form class="card auth-form" data-password-setup><label>New password<input name="password" type="password" minlength="8" autocomplete="new-password" required></label><label>Confirm password<input name="confirm_password" type="password" minlength="8" autocomplete="new-password" required></label><button class="button">Save password</button><p class="muted" data-password-message></p></form></section>`,env); }
function dashboard(env){ return shell('Creator dashboard',`<section class="card" data-dashboard><p class="eyebrow">CREATOR DASHBOARD</p><h1>Loading your prompt library…</h1></section>`,env); }
function admin(env){ return shell('Admin dashboard',`<section class="admin-app" data-admin><div class="admin-loading"><p class="eyebrow">ADMIN</p><h1>Loading your workspace…</h1></div></section>`,env); }
function home(env){ return shell('PromptHub',`<section class="home-grid"><div class="home-copy"><p class="eyebrow">YOUR PROMPTS, ONE LINK</p><h1>Turn “DM me for the prompt” into instant access.</h1><p class="lead">Share your PromptHub link in bio. Mention a keyword in your content. Your viewers enter it and instantly get the exact prompt.</p><div class="actions"><a class="button" href="/creator">Create your page →</a><a class="text-link" href="/c/demo?q=saree">See demo →</a></div></div></section>`,env); }
function privacy(env){ return shell('Privacy',`<section class="narrow prose"><p class="eyebrow">PRIVACY</p><h1>Privacy policy</h1><p>PromptHub stores the account and profile details a creator provides, published prompt content, and link activity metrics required to operate the service.</p><p>Authentication is provided through secure email links. We use account-session storage in the browser to keep a creator signed in. We do not ask for or receive a creator’s email password.</p><p>When advertising is enabled, advertising providers may use cookies or similar technologies to show and measure ads. Their processing is governed by their own policies.</p><p>We use service providers to host the application, deliver email, and store creator data. Access to private creator data is limited to the creator and authorised PromptHub administrators.</p><p>Last updated: 8 September 2026.</p></section>`,env); }
function terms(env){ return shell('Terms',`<section class="narrow prose"><p class="eyebrow">TERMS</p><h1>Terms of use</h1><p>PromptHub lets creators publish keyword-searchable AI prompts for their audience. Creators are responsible for the prompts, claims, and content they publish and must have the right to share them.</p><p>Do not use PromptHub for unlawful, harmful, deceptive, or infringing content. PromptHub may remove content or restrict access where needed to protect users or the service.</p><p>PromptHub is currently a creator beta. Features, limits, and policies may change as the product improves.</p><p>These terms may be updated as the product launches. Continued use after an update means acceptance of the revised terms.</p><p>Last updated: 8 September 2026.</p></section>`,env); }
export async function handleRequest(request,env){ const url=new URL(request.url), p=url.pathname; try { if(p==='/') return home(env); if(p==='/privacy') return privacy(env); if(p==='/terms') return terms(env); if(p==='/creator'||p==='/creator/login') return portal('creator',env); if(p==='/creator/set-password') return passwordSetup(env); if(p==='/dashboard') return dashboard(env); if(p==='/admin/login') return portal('admin',env); if(p==='/admin') return admin(env); if(p==='/health') return Response.json({status:'ok'}); const match=p.match(/^\/c\/([a-z0-9-]{3,30})$/); if(match){ const handle=match[1]; if(handle==='demo'){ const q=(url.searchParams.get('q')||'').trim().toLowerCase(); const item=q==='saree'?{keyword:'saree',title:'Shadowed Saree Elegance',prompt:'Create an editorial portrait of an adult woman wearing an elegant silk saree beside a softly lit window. Use warm natural light, detailed fabric textures and a balanced vertical composition.'}:null; const empty=q&&!item?`<article class="card empty"><h2>No prompt found for “${h(q)}”.</h2><p>Try the sample keyword saree.</p></article>`:''; return shell('PromptHub Demo',`<section class="viewer"><p class="eyebrow">PROMPTHUB DEMO</p><h1>Enter the keyword.</h1><form class="search"><input name="q" value="${h(q)}" placeholder="e.g. saree" required><button class="button">Get prompt →</button></form>${item?`<article class="card"><h2>${h(item.title)}</h2><pre>${h(item.prompt)}</pre><button class="button" data-copy>Copy prompt</button></article>`:empty}</section>`,env); } return shell('Creator page',`<section class="viewer" data-public-creator="${h(handle)}"><p class="eyebrow">CREATOR PAGE</p><h1>Loading prompts…</h1></section>`,env); } return shell('Not found','<section class="card"><h1>Page not found</h1></section>',env); } catch(error){ console.error(error); return shell('Unavailable','<section class="card"><h1>Temporarily unavailable</h1><p>Please try again shortly.</p></section>',env); } }








