const h = value => String(value ?? '').replace(/[&<>'"]/g, x => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[x]));
const config = env => ({ url: env.SUPABASE_URL || __APP_ENV__.SUPABASE_URL || '', key: env.SUPABASE_PUBLISHABLE_KEY || __APP_ENV__.SUPABASE_PUBLISHABLE_KEY || '' });
const headers = { 'Content-Type':'text/html; charset=utf-8', 'Cache-Control':'no-store', 'X-Content-Type-Options':'nosniff', 'Referrer-Policy':'strict-origin-when-cross-origin', 'Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' https://*.supabase.co; img-src 'self' https: data:; object-src 'none'; base-uri 'self'; form-action 'self'" };
function shell(title, content, env) { const c=config(env); return new Response(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${h(title)} · PromptHub</title><link rel="stylesheet" href="/css/v1.css"></head><body><header class="topbar"><a class="brand" href="/">Prompt<span>Hub</span><small>CREATORS</small></a><nav><a href="/c/demo">Try demo</a><a href="/creator">Creator portal</a><a href="/admin/login">Admin</a></nav></header><main>${content}</main><script>window.PROMPTHUB_SUPABASE=${JSON.stringify(c)}</script><script type="module" src="/js/supabase-portal.js"></script></body></html>`,{headers}); }
const fail=(message,status,env)=>shell('PromptHub',`<section class="card"><h1>Something went wrong</h1><p>${h(message)}</p></section>`,env).then?null:null;
async function db(env, path) { const c=config(env); if(!c.url||!c.key) throw new Error('Supabase runtime configuration is missing.'); const response=await fetch(c.url+'/rest/v1/'+path,{headers:{apikey:c.key,Authorization:'Bearer '+c.key}}); if(!response.ok) throw new Error('Data could not load.'); return response.json(); }
function portal(kind,env){ const admin=kind==='admin'; return shell(admin?'Admin login':'Creator portal',`<section class="creator-portal"><div><p class="eyebrow">${admin?'ADMIN PORTAL':'CREATOR PORTAL'}</p><h1>${admin?'Manage creators, revenue and payouts.':'Your prompts. Your link. Your audience.'}</h1><p class="lead">${admin?'Sign in with the administrator account.':'Sign up with email and password. Your viewers never need an account.'}</p><form class="card auth-form" data-auth="${admin?'admin':'creator'}"><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Password<input name="password" type="password" minlength="8" autocomplete="current-password" required></label><div class="actions"><button class="button" name="mode" value="signin">Sign in</button>${admin?'': '<button class="text-link" name="mode" value="signup">Create account</button>'}</div><p class="muted" data-auth-message></p></form></div><div class="card portal-steps"><span class="step-num">01</span><h2>${admin?'Secure role':'Create your page'}</h2><p>${admin?'Only users assigned the admin database role can open the admin dashboard.':'Choose your permanent bio-link handle after email verification.'}</p><span class="step-num">02</span><h2>${admin?'Review before payout':'Publish prompts'}</h2><p>${admin?'Approve the calculated ledger, then record the UPI payment reference.':'Add keywords and exact AI prompts.'}</p></div></section>`,env); }
function dashboard(env){ return shell('Creator dashboard',`<section class="card" data-dashboard><p class="eyebrow">CREATOR DASHBOARD</p><h1>Loading your prompt library…</h1></section>`,env); }
function admin(env){ return shell('Admin dashboard',`<section class="card" data-admin><p class="eyebrow">ADMIN</p><h1>Loading creator revenue…</h1></section>`,env); }
function home(env){ return shell('PromptHub',`<section class="home-grid"><div class="home-copy"><p class="eyebrow">YOUR PROMPTS, ONE LINK</p><h1>From your reel.<br>To their next creation.</h1><p class="lead">Creators publish prompts once. Viewers search a keyword and copy the exact prompt.</p><div class="actions"><a class="button" href="/creator">Create your page →</a><a class="text-link" href="/c/demo?q=saree">See demo →</a></div></div></section>`,env); }
export async function handleRequest(request,env){ const url=new URL(request.url), p=url.pathname; try { if(p==='/') return home(env); if(p==='/creator'||p==='/creator/login') return portal('creator',env); if(p==='/dashboard') return dashboard(env); if(p==='/admin/login') return portal('admin',env); if(p==='/admin') return admin(env); if(p==='/health') return Response.json({status:'ok'}); const match=p.match(/^\/c\/([a-z0-9-]{3,30})$/); if(match){ const handle=match[1]; const profiles=await db(env,`creator_profiles?select=id,handle,display_name,bio&handle=eq.${encodeURIComponent(handle)}&is_active=eq.true`); const owner=profiles[0]; if(!owner) return shell('Not found',`<section class="card"><h1>Creator page not found</h1></section>`,env); const q=(url.searchParams.get('q')||'').trim().toLowerCase(); let item=null; if(q){ const list=await db(env,`prompts?select=keyword,title,prompt,preview_path&creator_id=eq.${owner.id}&keyword=eq.${encodeURIComponent(q)}&status=eq.published`); item=list[0]; } return shell(owner.display_name,`<section class="viewer"><p class="eyebrow">${h(owner.display_name)}</p><h1>Enter the keyword.</h1><p>${h(owner.bio||'Find the exact AI prompt from this creator.')}</p><form class="search"><input name="q" value="${h(q)}" placeholder="e.g. saree" maxlength="80" required><button class="button">Get prompt →</button></form>${q?item?`<article class="card"><p class="eyebrow">${h(item.keyword)}</p><h2>${h(item.title)}</h2><pre>${h(item.prompt)}</pre><button class="button" data-copy>Copy prompt</button></article>`:`<p class="muted">No published prompt uses that keyword yet.</p>`:''}</section>`,env); } return shell('Not found','<section class="card"><h1>Page not found</h1></section>',env); } catch(error){ console.error(error); return shell('Unavailable','<section class="card"><h1>Temporarily unavailable</h1><p>Please try again shortly.</p></section>',env); } }


