const h = value => String(value ?? '').replace(/[&<>'"]/g, x => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[x]));
const config = env => ({ url: env.SUPABASE_URL || __APP_ENV__.SUPABASE_URL || '', key: env.SUPABASE_PUBLISHABLE_KEY || __APP_ENV__.SUPABASE_PUBLISHABLE_KEY || '', siteUrl: env.PUBLIC_SITE_URL || (env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${env.VERCEL_PROJECT_PRODUCTION_URL}` : '') });
const headers = { 'Content-Type':'text/html; charset=utf-8', 'Cache-Control':'no-store', 'X-Content-Type-Options':'nosniff', 'Referrer-Policy':'strict-origin-when-cross-origin', 'Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' https://*.supabase.co; img-src 'self' https: data:; object-src 'none'; base-uri 'self'; form-action 'self'" };
function shell(title, content, env) { const c=config(env); return new Response(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${h(title)} · PromptHub</title><link rel="stylesheet" href="/css/v1.css?v=creator-v2"><meta name="prompthub-supabase-url" content="${h(c.url)}"><meta name="prompthub-supabase-key" content="${h(c.key)}"><meta name="prompthub-site-url" content="${h(c.siteUrl)}"></head><body><header class="topbar"><a class="brand" href="/">Prompt<span>Hub</span><small>CREATORS</small></a></header><main>${content}</main><script type="module" src="/js/supabase-portal.js?v=creator-v3"></script></body></html>`,{headers}); }
const fail=(message,status,env)=>shell('PromptHub',`<section class="card"><h1>Something went wrong</h1><p>${h(message)}</p></section>`,env).then?null:null;
async function db(env, path) { if (path.includes('handle=eq.demo')) return [{id:'demo',handle:'demo',display_name:'PromptHub Demo',bio:'Try the keyword saree to see how a creator page works.'}]; if (path.includes('creator_id=eq.demo') && path.includes('keyword=eq.saree')) return [{keyword:'saree',title:'Shadowed Saree Elegance',prompt:'Create an editorial portrait of an adult woman wearing an elegant silk saree beside a softly lit window. Use warm natural light, detailed fabric textures and a balanced vertical composition.'}]; const c=config(env); if(!c.url||!c.key) throw new Error('Supabase runtime configuration is missing.'); const response=await fetch(c.url+'/rest/v1/'+path,{headers:{apikey:c.key,Authorization:'Bearer '+c.key}}); if(!response.ok) throw new Error('Data could not load.'); return response.json(); }
function portal(kind,env){
  const admin=kind==='admin';
  const creatorMagic=`<form class="card auth-form" data-magic-link><label>Email<input name="email" type="email" autocomplete="email" required></label><button class="button">Continue with email</button><p class="muted" data-magic-message></p></form>`;
  const adminLogin=`<form class="card auth-form" data-auth="admin"><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Password<input name="password" type="password" minlength="8" autocomplete="current-password" required></label><div class="actions"><button class="button" name="mode" value="signin">Sign in</button></div><p class="muted" data-auth-message></p></form>`;
  const login=admin?adminLogin:creatorMagic;
  return shell(admin?'Admin login':'Creator portal',`<section class="creator-portal"><div><p class="eyebrow">${admin?'ADMIN PORTAL':'CREATOR PORTAL'}</p><h1>${admin?'Manage creators, revenue and payouts.':'Start your creator page.'}</h1><p class="lead">${admin?'Sign in with the administrator account.':'Enter your email and we will send a secure sign-in link. No password required.'}</p>${login}</div><div class="card portal-steps"><span class="step-num">01</span><h2>${admin?'Secure role':'Check your inbox'}</h2><p>${admin?'Only users assigned the admin database role can open the admin dashboard.':'Open the one-time link we send to your email.'}</p><span class="step-num">02</span><h2>${admin?'Review before payout':'Create your page'}</h2><p>${admin?'Approve the calculated ledger, then record the UPI payment reference.':'Finish your creator profile, then publish your personal prompt link.'}</p></div></section>`,env);
}
function passwordSetup(env){ return shell('Set your password',`<section class="narrow"><p class="eyebrow">PROMPTHUB SECURITY</p><h1>Create a new password</h1><p class="lead compact">Choose a password for PromptHub. It is separate from your Gmail password.</p><form class="card auth-form" data-password-setup><label>New password<input name="password" type="password" minlength="8" autocomplete="new-password" required></label><label>Confirm password<input name="confirm_password" type="password" minlength="8" autocomplete="new-password" required></label><button class="button">Save password</button><p class="muted" data-password-message></p></form></section>`,env); }
function dashboard(env){ return shell('Creator dashboard',`<section class="card" data-dashboard><p class="eyebrow">CREATOR DASHBOARD</p><h1>Loading your prompt library…</h1></section>`,env); }
function admin(env){ return shell('Admin dashboard',`<section class="admin-app" data-admin><div class="admin-loading"><p class="eyebrow">ADMIN</p><h1>Loading your workspace…</h1></div></section>`,env); }
function home(env){ return shell('PromptHub',`<section class="home-grid"><div class="home-copy"><p class="eyebrow">YOUR PROMPTS, ONE LINK</p><h1>From your reel.<br>To their next creation.</h1><p class="lead">Creators publish prompts once. Viewers search a keyword and copy the exact prompt.</p><div class="actions"><a class="button" href="/creator">Create your page →</a><a class="text-link" href="/c/demo?q=saree">See demo →</a></div></div></section>`,env); }
export async function handleRequest(request,env){ const url=new URL(request.url), p=url.pathname; try { if(p==='/') return home(env); if(p==='/creator'||p==='/creator/login') return portal('creator',env); if(p==='/creator/set-password') return passwordSetup(env); if(p==='/dashboard') return dashboard(env); if(p==='/admin/login') return portal('admin',env); if(p==='/admin') return admin(env); if(p==='/health') return Response.json({status:'ok'}); const match=p.match(/^\/c\/([a-z0-9-]{3,30})$/); if(match){ const handle=match[1]; if(handle==='demo'){ const q=(url.searchParams.get('q')||'').trim().toLowerCase(); const item=q==='saree'?{keyword:'saree',title:'Shadowed Saree Elegance',prompt:'Create an editorial portrait of an adult woman wearing an elegant silk saree beside a softly lit window. Use warm natural light, detailed fabric textures and a balanced vertical composition.'}:null; return shell('PromptHub Demo',`<section class="viewer"><p class="eyebrow">PROMPTHUB DEMO</p><h1>Enter the keyword.</h1><form class="search"><input name="q" value="${h(q)}" placeholder="e.g. saree" required><button class="button">Get prompt →</button></form>${item?`<article class="card"><h2>${h(item.title)}</h2><pre>${h(item.prompt)}</pre><button class="button" data-copy>Copy prompt</button></article>`:''}</section>`,env); } return shell('Creator page',`<section class="viewer" data-public-creator="${h(handle)}"><p class="eyebrow">CREATOR PAGE</p><h1>Loading prompts…</h1></section>`,env); } return shell('Not found','<section class="card"><h1>Page not found</h1></section>',env); } catch(error){ console.error(error); return shell('Unavailable','<section class="card"><h1>Temporarily unavailable</h1><p>Please try again shortly.</p></section>',env); } }








